### ISSUE TITLE
ログを非表示にする

### ISSUE THREAD

**Issue by PIPOsen-0801** [anatawa12/plugin-permissions-for-ngt#17]
特定の手段(luckperms)でパーミッションをいじると、パーミッションが付与されていて、その動作ができているのに、パーミッションが付与されていない旨の表示が出てきます。そのため、その表示を出さないようにする設定ができるようにしてほしいです。

**Comment by anatawa12** [comment]
今調査したところログに表示する条件が逆になってますね。パーミッションがないときに表示させるログがパーミッションあるときに表示されるようになってるようです。すみません。
